version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/order_service

hooks:
  ApplicationStart:
    - location: Dependency_Scripts/startApplication.sh
      timeout: 600
      runas: ubuntu
